services:

    bondy:
        container_name: bondy
        image: leapsight/bondy:1.0.0-beta.67
        environment:
            BONDY_ERL_NODENAME: bondy@127.0.0.1
            BONDY_ERL_DISTRIBUTED_COOKIE: bondy
        env_file:
            - .env
        user: "0:1000"
        ports:
            # WS/HTTP
            - "18080:18080"
            # WS/HTTP Admin
            - "18081:18081"
            # TCP
            - "18082:18082"
            # HTTPS
            - "18083:18083"
            # Clustering
            - "18086:18086"
        volumes:
            - ./bondy/etc:/bondy/etc

    market:
        container_name: market
        extends:
            file: docker-compose.market.yml
            service: market
        depends_on:
            - bondy

    webapp:
        container_name: webapp
        build: ./webapp
        image: bondy-marketplace-webapp
        env_file:
            - .env
        ports:
            - "8080:80"
        depends_on:
            - bondy
            - market

    alice:
        container_name: alice
        extends:
            file: docker-compose.bot.yml
            service: bot
        command: Alice 3 10000 0.3 
        depends_on:
            - bondy
            - market

    tom:
        container_name: tom
        extends:
            file: docker-compose.bot.yml
            service: bot
        command: Tom 5 10000 0.5 
        depends_on:
            - bondy
            - market

    mary:
        container_name: mary
        extends:
            file: docker-compose.bot.yml
            service: bot
        command: Mary 7 10000 0.7 
        depends_on:
            - bondy
            - market

    victor:
        container_name: victor
        extends:
            file: docker-compose.bot.yml
            service: bot
        command: Victor 11 10000 1.1
        depends_on:
            - bondy
            - market
